name: Bug Report
description: File a bug report
labels: ["bug"]
assignees:
  - tjboldt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: Describe the problem.
    validations:
      required: true
  - type: dropdown
    id: hardware-version
    attributes:
      label: Hardware Version
      description: What version of the hardware are you running?
      options:
        - Seventh Prototype (lastest classic hardware)
        - RPi Pico
        - Sixth Prototype (classic hardware power jumper)
        - Fifth Prototype (classic hardware with EEPROM)
        - Fourth Prototype (classic hardware with EPROM)
    validations:
      required: true
  - type: dropdown
    id: firmware-version
    attributes:
      label: Firmware Version
      description: What version of the firmware are you running? (shown on boot screen)
      options:
        - 0011 / 8011 (add clock driver)
        - 0010 / 8010 (initial RPi Pico hardware)
        - 000F (first version showing firmware rev on boot)
        - Older (not shown on boot, pre-2022-Feb-07)
    validations:
      required: true
  - type: dropdown
    id: driver-version
    attributes:
      label: Driver Version
      description: What version of the driver are you running? Check with `RPI a2version`
      options:
        - 002E (fix driver crash on null drive)
        - 002D (add support for RPi Pico hardware)
        - 002C (fix nano editor)
        - 002B (fix keyboard delay)
        - 002A (reduce CPU usage)
        - 0029 (fix hang after shell exit)
        - 0028 (add live drive loading and regeneration)
        - 0027 (add dynamic drive support)
        - 0026 (add error handling)
        - 0025 (update RPi.command)
        - 0024 (fix VT100 arrow keys)
        - 0023 (replaced periph.io with rpio)
        - 0022 (added version info)
        - Older (error calling RPI a2version, pre-2022-Feb-07)
    validations:
      required: true
  - type: dropdown
    id: shell-version
    attributes:
      label: Shell Version
      description: What version of the shell are you running?`
      options:
        - 0010 / 8010 (support latest firmware)
        - 000F / 800F (add pico and classic hardware support)
        - 000E (fix hang on exit)
        - 000D (added version info)
        - Older (pre-2022-Mar-01)
        - Not Applicable (bug not Shell related)
    validations:
      required: true
  - type: dropdown
    id: problem-area
    attributes:
      label: Where are you seeing this problem?
      options:
        - Boot
        - ProDOS access
        - SHELL command
        - RPI Command
        - Other
    validations:
      required: true
  - type: dropdown
    id: computer
    attributes:
      label: What computer is this running on?
      options:
        - Apple II
        - Apple II+
        - Apple //e (unenhanced)
        - Apple //e (enhanced / platinum)
        - Apple IIgs
        - Clone II+
        - Other
    validations:
      required: true      
