name: Assembler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build firmare
      run: |
        export PATH=$PATH:$(pwd)/.cicd
        cd Apple2
        ./assemble.sh
        
